mod agent;
mod agent_sandbox;
mod app_store;
mod dependabot;
mod error;
mod forge;
mod fsops;
mod funding;
mod git;
mod github;
mod health;
mod hooks;
mod instructions;
mod jira_field_maps;
mod jira_links;
mod local_issues;
mod local_prs;
mod mcp;
mod mcp_launcher;
mod mcp_server;
mod oplog;
mod path_launcher;
mod pty;
mod research;
mod secrets;
mod sessions;
mod state;
mod tray;

use state::AppState;

pub use mcp_server::run_mcp_server;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = tauri::Builder::default();
    // Single-instance lock, release builds only: a second launch defers to the
    // running instance, whose callback brings the window back (incl. restoring
    // it from the tray) instead of starting a duplicate — two instances each
    // running automations double-post (duplicate-AI-review incident, 2026-07-10;
    // the store plugin caches app-data per process, so instances can't dedup
    // through the store). Dev is exempt on purpose: the lock keys on the shared
    // `com.thebguy.gitdesktop` identifier, and dev+prod / two dev builds
    // (parallel-worktree testing) must keep coexisting. Keep this the FIRST
    // plugin registered so the check runs before any other init. The second
    // launch's argv/cwd are intentionally dropped: v1 is focus-only, and no
    // CLI repo-open feature exists to forward them to.
    #[cfg(all(desktop, not(debug_assertions)))]
    let builder = builder.plugin(tauri_plugin_single_instance::init(|app, _argv, _cwd| {
        tray::show_main_window(app);
    }));
    builder
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_http::init())
        .plugin(tauri_plugin_notification::init())
        .plugin(tauri_plugin_store::Builder::new().build())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_process::init())
        // Remembers the window's position, size, and maximized state across
        // launches (and validates saved coords against the current monitors, so
        // an unplugged display can't strand the window off-screen). We persist
        // GEOMETRY only — not visibility: the tray logic owns whether the window is
        // shown, and a saved "hidden" would reopen it invisible. The save itself is
        // driven from the window-close handler (tray.rs), since `tauri dev` is
        // usually killed rather than cleanly exited and close-to-tray isn't a real
        // close — so the plugin's own save-on-exit can't be relied on.
        .plugin(
            tauri_plugin_window_state::Builder::default()
                .with_state_flags(tray::WINDOW_STATE_FLAGS)
                .build(),
        )
        .setup(|app| {
            // Desktop-only auto-updater (GitHub Releases). No-op on mobile.
            #[cfg(desktop)]
            {
                app.handle()
                    .plugin(tauri_plugin_updater::Builder::new().build())?;
                tray::setup_tray(app.handle())?;
                tray::init_window_title(app.handle());
                // On Windows, keep the managed MCP launcher copy fresh after an
                // update — but only if it already exists (lazy: never-used ⇒
                // never copied). Fire-and-forget so startup never blocks on the
                // ~50MB copy; a stale copy still serves running sessions.
                #[cfg(windows)]
                {
                    let version = app.package_info().version.to_string();
                    tauri::async_runtime::spawn_blocking(move || {
                        mcp_launcher::refresh_if_present(&version);
                    });
                }
            }
            Ok(())
        })
        .on_window_event(tray::handle_window_event)
        .manage(AppState::default())
        .manage(pty::PtyState::default())
        .invoke_handler(tauri::generate_handler![
            git::repo::check_git_installed,
            git::repo::validate_repo,
            git::repo::clone_repo,
            git::repo::create_repo,
            git::repo::git_repo_owners,
            git::repo::git_repo_identity,
            git::status::git_status,
            git::branches::git_branches,
            git::branches::git_remote_branches,
            git::branches::git_checkout_branch,
            git::branches::git_checkout_remote_branch,
            git::branches::git_create_branch,
            git::branches::git_rename_branch,
            git::branches::git_delete_branch,
            git::branches::git_delete_remote_branch,
            git::branches::git_default_branch,
            git::branches::git_branch_divergence,
            git::branches::git_branch_merge_states,
            git::branches::git_set_branch_archived,
            git::branches::git_update_branch_from,
            git::branches::commit_on_remote,
            git::branches::git_unpushed_count,
            git::diff::git_diff_file,
            git::diff::git_session_file_diff,
            git::diff::git_staged_diff,
            git::diff::git_apply_patch,
            git::diff::git_apply_partial,
            git::diff::git_file_base64,
            git::stage::git_stage,
            git::stage::git_unstage,
            git::commit::git_commit,
            git::commit::git_commit_authors,
            git::commit::git_user_identity,
            git::commit::git_local_identity,
            git::commit::git_set_local_identity,
            git::commit::git_global_identity,
            git::commit::git_set_global_identity,
            git::commit::git_global_default_branch,
            git::commit::git_set_global_default_branch,
            git::config::git_global_autocrlf,
            git::config::git_set_global_autocrlf,
            git::commit::git_undo_commit,
            git::commit::git_recent_commits,
            git::history::git_log,
            git::history::git_file_log,
            git::history::git_blame,
            git::history::git_commit_details,
            git::history::git_commit_files,
            git::history::git_commit_file_diff,
            git::history::git_commit_diff,
            git::ops::git_discard,
            git::ops::git_discard_untracked_lines,
            git::ops::git_reset,
            git::worktree::git_worktree_create,
            git::worktree::git_worktree_list,
            git::worktree::git_worktree_list_user,
            git::worktree::git_worktree_add_user,
            git::worktree::git_worktree_move,
            git::worktree::git_worktree_lock,
            git::worktree::git_worktree_unlock,
            git::worktree::git_worktree_repair,
            git::worktree::git_worktree_remove,
            git::worktree::git_worktree_prune,
            git::worktree::git_worktree_commit_all,
            git::worktree::git_worktree_squash,
            git::worktree::git_worktree_resume,
            sessions::transcript_load_all,
            sessions::transcript_create,
            sessions::transcript_append_turn,
            sessions::transcript_append_result,
            sessions::transcript_append_meta,
            sessions::transcript_set_kept,
            sessions::transcript_remove,
            agent_sandbox::agent_container_detect,
            agent_sandbox::agent_container_prepare,
            agent_sandbox::agent_custom_image_status,
            agent_sandbox::agent_build_custom_image,
            agent_sandbox::agent_scaffold_custom_dockerfile,
            agent_sandbox::agent_sandbox_cleanup,
            agent_sandbox::agent_open_container_shell,
            agent_sandbox::agent_test_container_running,
            agent_sandbox::agent_stop_test_container,
            pty::pty_open,
            pty::pty_write,
            pty::pty_resize,
            pty::pty_close,
            git::ops::git_checkout_commit,
            git::ops::git_revert,
            git::ops::git_cherry_pick,
            git::ops::git_cherry_pick_onto,
            git::ops::git_rewrite_commits,
            git::ops::git_rebase_edit,
            git::ops::git_unpushed_messages,
            git::ops::git_tag,
            git::ops::git_push_tag,
            git::ops::git_delete_tag,
            git::ops::git_list_tags,
            git::ops::git_discard_all,
            git::ops::git_discard_paths,
            git::ops::git_stash_all,
            git::ops::git_stash_paths,
            git::ops::git_untrack,
            git::ops::git_list_tracked,
            git::ops::git_ignored_files,
            git::ops::git_force_add,
            git::ops::git_unignore_rules,
            git::ops::git_replace_file_lines,
            git::ops::git_stash_pop,
            git::ops::git_stash_count,
            git::ops::git_stash_list,
            git::ops::git_stash_files,
            git::ops::git_stash_file_diff,
            git::ops::git_stash_apply,
            git::ops::git_stash_drop,
            git::ops::git_orphaned_stashes,
            git::ops::git_orphaned_stash_files,
            git::ops::git_orphaned_stash_file_diff,
            git::ops::git_restore_orphaned,
            oplog::git_oplog_list,
            oplog::git_oplog_check,
            oplog::git_oplog_dismiss,
            git::ops::git_merge,
            git::ops::git_merge_preview,
            git::ops::git_rebase,
            git::ops::git_rebase_onto,
            git::ops::git_op_state,
            git::ops::git_op_abort,
            git::ops::git_op_continue,
            git::ops::git_merge_local_pr,
            git::ops::git_finish_local_pr_merge,
            git::ops::git_abort_local_pr_merge,
            git::ops::git_cleanup_orphaned_resolve_worktrees,
            git::ops::git_conflict_preview,
            git::conflict::git_conflict_sides,
            git::conflict::git_resolve_conflict,
            git::conflict::git_checkout_conflict_side,
            git::conflict::git_diff_contents,
            git::stats::git_repo_stats,
            git::stats::git_branch_stats,
            git::stats::git_contributor_activity,
            git::stats::git_commit_activity,
            git::stats::git_code_frequency,
            git::stats::git_punch_card,
            git::compare::git_compare_branches,
            git::compare::git_branch_diff_files,
            git::compare::git_branch_file_diff,
            git::compare::git_branch_diff,
            git::compare::git_diff_between_refs,
            git::compare::git_grep_at_ref,
            git::compare::git_fetch_objects,
            git::compare::git_branch_tips,
            git::compare::git_review_worktree,
            git::compare::git_remove_worktree,
            forge::forge_status,
            forge::forge_bb_set_account,
            forge::forge_bb_clear_account,
            forge::forge_bb_account,
            forge::forge_bb_step_logs,
            forge::jira_set_account,
            forge::jira_set_account_from_bitbucket,
            forge::jira_account,
            forge::jira_clear_account,
            forge::jira_validate,
            forge::jira_project_search,
            forge::jira_issue_list,
            forge::jira_issue_view,
            forge::jira_issue_comment,
            forge::jira_issue_transition,
            forge::jira_issue_transitions,
            forge::jira_issue_transition_to,
            forge::jira_issue_create,
            forge::jira_issue_types,
            forge::jira_issue_assign,
            forge::jira_user_search,
            forge::jira_permissions,
            forge::forge_list_repos,
            forge::forge_clone,
            forge::forge_pr_list,
            forge::forge_pr_poll,
            forge::forge_prs_for_branch,
            forge::forge_pr_view,
            forge::forge_pr_timeline,
            forge::forge_pr_diff,
            forge::forge_pr_commit_diff,
            forge::forge_commit_comments,
            forge::forge_commit_comment_create,
            forge::forge_commit_comment_edit,
            forge::forge_commit_comment_delete,
            forge::forge_pr_external_reviews,
            forge::forge_pr_review_threads,
            forge::forge_pr_thread_reply,
            forge::forge_pr_thread_create,
            forge::forge_pr_review_submit,
            forge::forge_pr_thread_resolve,
            forge::forge_issue_list,
            forge::forge_issue_view,
            forge::forge_ci_run_list,
            forge::forge_ci_run_view,
            forge::forge_ci_run_failed_logs,
            forge::forge_ci_job_logs,
            forge::forge_ci_run_rerun,
            forge::forge_ci_run_cancel,
            forge::forge_ci_dispatch,
            forge::forge_release_list,
            forge::forge_release_view,
            forge::forge_release_create,
            forge::forge_release_edit,
            forge::forge_release_delete,
            forge::forge_release_upload_asset,
            forge::forge_release_delete_asset,
            forge::forge_issue_comment,
            forge::forge_issue_edit_comment,
            forge::forge_issue_delete_comment,
            forge::forge_issue_close,
            forge::forge_issue_reopen,
            forge::forge_issue_edit,
            forge::forge_issue_lock,
            forge::forge_issue_unlock,
            forge::forge_issue_transfer,
            forge::forge_issue_delete,
            forge::forge_repo_admin,
            forge::forge_gl_repo_settings,
            forge::forge_gl_repo_settings_update,
            forge::forge_gl_members,
            forge::forge_gl_member_add,
            forge::forge_gl_member_update,
            forge::forge_gl_member_remove,
            forge::forge_gl_hooks,
            forge::forge_gl_hook_create,
            forge::forge_gl_hook_update,
            forge::forge_gl_hook_delete,
            forge::forge_gl_hook_test,
            forge::forge_gl_hook_events,
            forge::forge_gl_hook_resend,
            forge::forge_gl_variables,
            forge::forge_gl_variable_set,
            forge::forge_gl_variable_delete,
            forge::forge_gl_protected_branches,
            forge::forge_gl_protected_branch_create,
            forge::forge_gl_protected_branch_update,
            forge::forge_gl_protected_branch_delete,
            forge::forge_gl_member_projects,
            forge::forge_gl_mr_merge_state,
            forge::forge_gl_mr_auto_merge,
            forge::forge_gl_mr_cancel_auto_merge,
            forge::forge_gl_ci_play_job,
            forge::forge_gl_issue_time_stats,
            forge::forge_gl_mr_time_stats,
            forge::forge_gl_issue_set_time_estimate,
            forge::forge_gl_issue_add_spent_time,
            forge::forge_gl_mr_set_time_estimate,
            forge::forge_gl_mr_add_spent_time,
            forge::forge_gl_issue_links,
            forge::forge_gl_issue_link,
            forge::forge_gl_issue_unlink,
            forge::forge_repo_rename,
            forge::forge_repo_set_archived,
            forge::forge_repo_set_visibility,
            forge::forge_repo_transfer,
            forge::forge_repo_delete,
            forge::forge_milestones,
            forge::forge_issue_set_milestone,
            forge::forge_gl_issue_set_confidential,
            forge::forge_gl_issue_set_due_date,
            forge::forge_issue_reactions,
            forge::forge_pr_reactions,
            forge::forge_add_reaction,
            forge::forge_remove_reaction,
            forge::forge_pr_comment,
            forge::forge_gitlab_review_token_status,
            forge::forge_gitlab_review_token_set,
            forge::forge_gitlab_review_token_clear,
            forge::forge_pr_edit_comment,
            forge::forge_pr_delete_comment,
            forge::forge_pr_edit_review_comment,
            forge::forge_pr_delete_review_comment,
            forge::forge_pr_close,
            forge::forge_pr_reopen,
            forge::forge_pr_edit,
            forge::forge_pr_approvals,
            forge::forge_pr_approve,
            forge::forge_pr_unapprove,
            forge::forge_pr_request_changes,
            forge::forge_pr_unrequest_changes,
            forge::forge_pr_set_draft,
            forge::forge_pr_set_reviewers,
            forge::forge_pr_reviewer_candidates,
            forge::forge_pr_merge,
            forge::forge_repo_labels,
            forge::forge_assignable_users,
            forge::forge_edit_labels,
            forge::forge_issue_set_assignees,
            forge::forge_mr_set_assignees,
            forge::forge_issue_create,
            forge::forge_pr_create,
            forge::forge_repo_url,
            forge::forge_repo_star_status,
            forge::forge_repo_set_star,
            forge::forge_repo_visibility,
            forge::forge_publish_targets,
            forge::forge_publish_repo,
            forge::forge_bb_workspaces,
            forge::forge_bb_repo_settings,
            forge::forge_bb_repo_settings_update,
            forge::forge_bb_default_reviewers,
            forge::forge_bb_default_reviewer_add,
            forge::forge_bb_default_reviewer_remove,
            forge::forge_bb_member_candidates,
            forge::forge_bb_branch_restrictions,
            forge::forge_bb_branch_restriction_create,
            forge::forge_bb_branch_restriction_update,
            forge::forge_bb_branch_restriction_delete,
            forge::forge_bb_pipelines_config,
            forge::forge_bb_pipelines_config_update,
            forge::forge_bb_pipeline_variables,
            forge::forge_bb_pipeline_variable_create,
            forge::forge_bb_pipeline_variable_update,
            forge::forge_bb_pipeline_variable_delete,
            forge::forge_bb_pipeline_schedules,
            forge::forge_bb_pipeline_schedule_create,
            forge::forge_bb_pipeline_schedule_set_enabled,
            forge::forge_bb_pipeline_schedule_delete,
            forge::forge_bb_hooks,
            forge::forge_bb_hook_create,
            forge::forge_bb_hook_update,
            forge::forge_bb_hook_delete,
            forge::forge_bb_pr_tasks,
            forge::forge_bb_pr_task_create,
            forge::forge_bb_pr_task_edit,
            forge::forge_bb_pr_task_set_state,
            forge::forge_bb_pr_task_delete,
            forge::forge_bb_custom_pipelines,
            forge::forge_bb_environments,
            github::pr::gh_status,
            github::pr::gh_accounts,
            github::pr::gh_switch_account,
            github::pr::gh_list_repos,
            github::pr::gh_pr_create,
            github::pr::gh_repo_url,
            github::pr::gh_publish_repo,
            github::pr::gh_prs_for_branch,
            github::pr::gh_pr_list,
            github::pr::gh_pr_poll,
            github::pr::gh_pr_view,
            github::pr::gh_pr_diff,
            github::pr::gh_pr_external_reviews,
            github::pr::gh_pr_review,
            github::pr::gh_pr_comment,
            github::pr::gh_pr_minimize_comment,
            github::pr::gh_pr_unminimize_comment,
            github::pr::gh_pr_merge,
            github::pr::gh_pr_close,
            github::pr::gh_pr_reopen,
            github::pr::gh_pr_checkout,
            github::pr::gh_pr_reactions,
            github::pr::gh_repo_fork,
            github::pr::gh_repo_star_status,
            github::pr::gh_repo_set_star,
            github::issue::gh_issue_list,
            github::issue::gh_issue_view,
            github::issue::gh_issue_create,
            github::issue::gh_issue_comment,
            github::issue::gh_issue_close,
            github::issue::gh_issue_reopen,
            github::issue::gh_issue_edit,
            github::issue::gh_assignable_users,
            github::issue::gh_milestones,
            github::issue::gh_issue_set_assignees,
            github::issue::gh_issue_set_milestone,
            github::issue::gh_issue_types,
            github::issue::gh_issue_set_type,
            github::issue::gh_issue_pin,
            github::issue::gh_issue_unpin,
            github::issue::gh_issue_lock,
            github::issue::gh_issue_unlock,
            github::issue::gh_issue_reactions,
            github::issue::gh_add_reaction,
            github::issue::gh_remove_reaction,
            github::issue::gh_issue_transfer,
            github::issue::gh_issue_delete,
            github::issue::gh_issue_relations,
            github::issue::gh_issue_add_sub_issue,
            github::issue::gh_issue_remove_sub_issue,
            github::issue::gh_issue_dependencies,
            github::issue::gh_issue_set_dependency,
            github::issue::gh_issue_development,
            github::issue::gh_issue_create_linked_branch,
            github::issue::read_issue_templates,
            github::discussion::gh_discussion_categories,
            github::discussion::gh_discussion_list,
            github::discussion::gh_discussion_view,
            github::discussion::gh_discussion_create,
            github::discussion::gh_discussion_add_comment,
            github::discussion::gh_discussion_mark_answer,
            github::discussion::gh_discussion_unmark_answer,
            github::discussion::gh_discussion_update_comment,
            github::discussion::gh_discussion_delete_comment,
            github::discussion::gh_discussion_set_upvote,
            github::discussion::gh_discussion_reactions,
            github::discussion::gh_discussion_lock,
            github::discussion::gh_discussion_unlock,
            github::discussion::gh_discussion_close,
            github::discussion::gh_discussion_reopen,
            github::discussion::gh_discussion_delete,
            github::repo_settings::gh_repo_admin,
            github::auth::gh_token_scopes,
            github::collaborators::gh_collaborators_list,
            github::collaborators::gh_collaborator_add,
            github::collaborators::gh_collaborator_remove,
            github::collaborators::gh_invitations_list,
            github::collaborators::gh_invitation_update,
            github::collaborators::gh_invitation_cancel,
            github::security::gh_security_get,
            github::security::gh_security_apply,
            github::lifecycle::gh_repo_set_visibility,
            github::lifecycle::gh_repo_transfer,
            github::lifecycle::gh_repo_delete,
            github::lifecycle::gh_repo_set_archived,
            github::lifecycle::gh_repo_rename,
            github::pages::gh_pages_get,
            github::pages::gh_pages_enable,
            github::pages::gh_pages_update,
            github::pages::gh_pages_disable,
            github::rulesets::gh_rulesets_list,
            github::rulesets::gh_ruleset_get,
            github::rulesets::gh_ruleset_create,
            github::rulesets::gh_ruleset_update,
            github::rulesets::gh_ruleset_delete,
            github::rulesets::gh_ruleset_set_enforcement,
            github::secrets::gh_secrets_list,
            github::secrets::gh_secret_set,
            github::secrets::gh_secret_delete,
            github::secrets::gh_variables_list,
            github::secrets::gh_variable_set,
            github::secrets::gh_variable_delete,
            github::secrets::gh_environments_list,
            funding::funding_get,
            funding::funding_set,
            funding::funding_delete,
            research::research_save_report,
            dependabot::dependabot_get,
            dependabot::dependabot_set,
            dependabot::dependabot_delete,
            github::insights::gh_community_insights,
            github::insights::gh_repo_traffic,
            github::insights::gh_repo_dependencies,
            github::insights::gh_repo_stats,
            github::mcp_search::gh_github_mcp_search,
            github::repo_settings::gh_hooks_list,
            github::repo_settings::gh_hook_create,
            github::repo_settings::gh_hook_update,
            github::repo_settings::gh_hook_delete,
            github::repo_settings::gh_hook_ping,
            github::repo_settings::gh_hook_test,
            github::repo_settings::gh_hook_deliveries,
            github::repo_settings::gh_hook_delivery,
            github::repo_settings::gh_hook_redeliver,
            github::repo_settings::gh_repo_settings_get,
            github::repo_settings::gh_repo_settings_update,
            github::release::gh_release_list,
            github::release::gh_release_view,
            github::release::gh_release_create,
            github::release::gh_release_edit,
            github::release::gh_release_generate_notes,
            github::release::gh_release_delete,
            github::release::gh_release_upload_asset,
            github::release::gh_release_delete_asset,
            github::release::gh_release_download_asset,
            github::pr::gh_pr_ready,
            github::pr::gh_pr_edit,
            github::pr::gh_repo_labels,
            github::pr::gh_branch_protections,
            github::pr::gh_pr_edit_labels,
            github::actions::gh_run_list,
            github::actions::gh_run_view,
            github::actions::gh_run_rerun,
            github::actions::gh_run_cancel,
            github::actions::gh_run_failed_logs,
            github::actions::gh_job_logs,
            github::actions::gh_workflow_list,
            github::actions::gh_workflow_run,
            fsops::append_to_gitignore,
            fsops::read_text_file,
            fsops::delete_repo_folder,
            fsops::reveal_in_explorer,
            fsops::open_with_default,
            fsops::open_in_terminal,
            fsops::open_with_program,
            fsops::detect_editors,
            fsops::detect_terminals,
            mcp_launcher::mcp_launcher_path,
            path_launcher::path_launcher_status,
            path_launcher::path_launcher_install,
            path_launcher::path_launcher_remove,
            git::remote::git_fetch,
            git::remote::git_pull,
            git::remote::git_push,
            git::remote::git_remotes,
            git::remote::git_remote_url,
            git::remote::git_remote_set_url,
            git::submodule::git_submodules,
            git::submodule::git_submodule_update,
            secrets::set_secret,
            secrets::get_secret,
            secrets::delete_secret,
            secrets::secret_exists,
            secrets::set_mcp_secret,
            secrets::delete_mcp_secret,
            secrets::mcp_secret_exists,
            mcp::discover_mcp_servers,
            mcp::mcp_json_write,
            mcp::mcp_global_install,
            mcp::mcp_global_status,
            mcp::mcp_global_remove,
            instructions::read_repo_instructions,
            instructions::read_repo_ai_ignore,
            instructions::read_repo_branch_rules,
            instructions::write_repo_branch_rules,
            instructions::read_repo_syntax,
            instructions::write_repo_syntax,
            instructions::read_agent_commands,
            hooks::git_hooks_list,
            hooks::git_hook_read,
            hooks::git_hook_write,
            hooks::git_hook_set_enabled,
            hooks::git_hook_delete,
            hooks::git_run_hook_manager,
            agent::agent_detect,
            health::system_health,
            agent::agent_review,
            agent::agent_review_cancel,
            agent::agent_session,
            tray::set_close_to_tray,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
